# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b578936babe95a92dbe8e18ebba24ec1bf1081c9654fbe564ad2516284e1543787a96c9f22734f7edc49e2d13e4f9e2db8ad29e7704cdda5b251c64862cec0ef

test:
  secret_key_base: 31e9f1a81423ad6df88fdd638717eee1f121a392ac8f1ee3179a947b868b2e410229277164dc58d2d01dd12db328cce118191f1a07b2a1a31d3e199098381e5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
